### PR TITLE
Event list fixes

### PR DESCRIPTION
**Pull request by jonahanderson**
This code changes the event list table into a bootstrap-table with the css and js files I have created.

In doing so, a user can click on the title column on the table:
- By name of attendee in alphabetized ascending and descending order (previous behavior was sorting automatically - this behavior still exists)
- By user who added attendee to list in alphabetized ascending and descending order (no behavior for sorting by user existed previously)

Originally, I looked into why the user's name was not showing up under the user column when adding attendees. I noticed that it still does that, but leaves it blank if there is no name of the user (the admin account has no name, so I mistakenly believed this to be a bug, but its not). Everyone who creates an account should create a name, so fixing this would be unnecessary.

**NOTE** 
With this change, if a user activates party mode and starts crossing off people on the list, and then sorts through some columns, it takes a couple seconds for some attendees to get crossed out. still looking into this behavior.

An additional small bug that I am noticing is that if one were to toggle party mode, check a name, and then turn party mode off, their name is still in red. unsure if this is intended?

### CODE REVIEW

**Comment by jonahanderson** [comment]
I like this, especially since it fixes the issue with the delay of names being cross out after sorting in party mode. However, I think we might want to extend the clickability of the icon to sort- maybe the entire th cell? what do you think? @csyager

**Comment by jonahanderson** [comment]
looks good to me, you have to review it tho. thanks for fixing the issues

**Review by csyager — APPROVED** [review]

**Comment by jonahanderson** [comment]
yea this is really good, good job - way better than I originally did it.

**Comment by sidneyjennings** [comment]
Everything works well on my end. I briefly read the new js code, but that's outside of my expertise

**Review by sidneyjennings — APPROVED** [review]

**Pull request merged**
